# Document:
# http://simiki.org/docs/configuration.html

url: http://wiki.lostsumme.love 
title: Wiki of Lostsummer
keywords: c, python, go, docker, influxdb
description: My Personal wiki.
author: Lostsummer

theme: yasimple

deploy:
    - type: git
